#!/usr/bin/env bash
# This script outputs numbers from 1 to 100 with FizzBuzz conditions

Count=1
while ((Count <= 100)); do
    if [ "$((Count % 3))" -eq 0 ] && [ "$((Count % 5))" -eq 0 ]; then
        echo "FizzBuzz"
    elif [ "$((Count % 3))" -eq 0 ]; then
        echo "Fizz"
    elif [ "$((Count % 5))" -eq 0 ]; then
        echo "Buzz"
    else
        echo "$Count"
    fi
    ((Count++))
done
