#!/usr/bin/env bash
#This script is to output Best school 10 times using while loop with the 8th one and the 4th one having different output 
Count=0
while((Count<10));do
	if [ "$Count" -eq 7 ] ;then
		echo "good luck"
	elif [ "$Count" -eq 3 ] ;then
		echo "bad luck"
	else 
		echo "Best School"
	fi
((Count++))
done;
