#!/usr/bin/env bash
#This script test a file for various outcomes
Files=$( find . -name "school" |cut -d "/" -f2)
if [ -e "$Files" ] ;then
	echo "school file exists"
	if [ -s "$Files" ] ;then
		echo "school file is not empty"
	elif [ ! -s "$Files" ] ;then
		echo "school file is empty"
	fi
	if [ -f "$Files" ] ;then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
